version: '3.8'
services:
  diet-analysis:
    build: .
    container_name: diet-analysis-container
    volumes:
      - ./charts:/app/charts
      - ./simulated_nosql:/app/simulated_nosql
    environment:
      - PYTHONUNBUFFERED=1